name: fast-speedtest
version: "1.0.1"
summary: fast speedtest client
description: measure download speed using fast.
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: i386
    run-on: i386
  - build-on: armhf
    run-on: armhf

apps:
  fast-speedtest:
    command: bin/fast
    plugs: [network, network-bind]

parts:
  fast-speedtest:
    plugin: nodejs
    node-engine: 11.15.0
